version: '3.7'

services:
  workout-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/app/src
    container_name: workout-tracker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run start
    
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - app-db:/var/lib/postgresql/data
